---
version: "2.0"

services:
  app:
    image: dimokus88/massa:9.0.2
    env:
    # - my_discord_id="your_discord_id "
    # - my_wallet_privkey="your_wallet_privat_key"
    # - my_wallet_addr="your_wallet_address"
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
          
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 4Gi
        storage:
          size: 20Gi
  placement:
    akash:
      pricing:
        app:
          denom: uakt
          amount: 100
deployment:
  app:
    akash:
      profile: app
      count: 1 #max 2 count
