---
version: "2.0"
services:
  app:
    image: ubuntu:latest
    expose:
      - port: 80
        as: 80
        proto: tcp
        to:
          - global: true
            
      - port: 22
        as: 22
        proto: tcp
        to:
          - global: true

      - port: 31244
        as: 31244
        proto: tcp
        to:
          - global: true

      - port: 31245
        as: 31245
        proto: tcp
        to:
          - global: true
    env:
     - "my_discord_id="
     - "my_wallet_privkey=" #Massa wallet privat key
     - "my_root_password=" #For ssh connection
     - "wait=600" #Set roll check frequency in seconds. Установите частоту проверки роллов в секундах.
     - "MASSA_LINK=https://github.com/massalabs/massa/releases/download/TEST.15.1/massa_TEST.15.1_release_linux.tar.gz"
     - "pass=111111"
   
    command:
      - "bash"
      - "-c"
    args:
      - 'apt-get update ; apt-get upgrade -y ; apt-get install -y  curl ; curl -s  https://raw.githubusercontent.com/Dimokus88/Massa/main/massa.sh  | bash ; sleep infinity '

profiles:
  compute:
    app:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 4Gi
        storage:
          size: 25Gi

  placement:
    akash: 
      attributes:
            
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
