---
version: "2.0"

services:
  app:
    image: dimokus88/massa:11.1.3
    env:
     - "my_discord_id=your_discord_id"
     - "my_wallet_privkey=your_wallet_privat_key" #Massa wallet privat key
     - "my_root_password=your_root_password" #For ssh connection
     - "MASSA_LINK=https://github.com/massalabs/massa/releases/download/TEST.11.3/massa_TEST.11.3_release_linux.tar.gz"
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
          
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 4Gi
        storage:
          size: 50Gi
  placement:
    akash:
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 #max 2 count
